name: Deploy

on:
  push:
    branches:
      - production 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "pap-bot"
          heroku_email:  ${{secrets.CREATOR_EMAIL}}
        env:
          HD_NODE_ENV: production
          HD_BOT_ID: ${{secrets.BOT_ID}}
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_DATABASE_URL: ${{secrets.DATABASE_URL}}
          HD_GCALENDAR_CLIENT_ID: ${{secrets.GCALENDAR_CLIENT_ID}}
          HD_GCALENDAR_PROJECT_ID: ${{secrets.GCALENDAR_PROJECT_ID}}
          HD_GCALENDAR_CLIENT_SECRET: ${{secrets.GCALENDAR_CLIENT_SECRET}}
          HD_GCALENDAR_ACCESS_TOKEN: ${{secrets.GCALENDAR_ACCESS_TOKEN}}
          HD_GCALENDAR_REFRESH_TOKEN: ${{secrets.GCALENDAR_REFRESH_TOKEN}}
          HD_GMAIL_CLIENT_ID: ${{secrets.GMAIL_CLIENT_ID}}
          HD_GMAIL_PROJECT_ID: ${{secrets.GMAIL_PROJECT_ID}}
          HD_GMAIL_CLIENT_SECRET: ${{secrets.GMAIL_CLIENT_SECRET}}
          HD_GMAIL_ACCESS_TOKEN: ${{secrets.GMAIL_ACCESS_TOKEN}}
          HD_GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN}}
          HD_GDRIVE_FILE_ID: ${{secrets.GDRIVE_FILE_ID}}
          HD_GDRIVE_CLIENT_ID : ${{secrets.GDRIVE_CLIENT_ID}}
          HD_GDRIVE_PROJECT_ID: ${{secrets.GDRIVE_PROJECT_ID}}
          HD_GDRIVE_CLIENT_SECRET: ${{secrets.GDRIVE_CLIENT_SECRET}}
          HD_GDRIVE_ACCESS_TOKEN: ${{secrets.GDRIVE_ACCESS_TOKEN}}
          HD_GDRIVE_REFRESH_TOKEN: ${{secrets.GDRIVE_REFRESH_TOKEN}}
          HD_GSHEETS_CLIENT_ID : ${{secrets.GSHEETS_CLIENT_ID}}
          HD_GSHEETS_PROJECT_ID: ${{secrets.GSHEETS_PROJECT_ID}}
          HD_GSHEETS_CLIENT_SECRET: ${{secrets.GSHEETS_CLIENT_SECRET}}
          HD_GSHEETS_ACCESS_TOKEN: ${{secrets.GSHEETS_ACCESS_TOKEN}}
          HD_GSHEETS_REFRESH_TOKEN: ${{secrets.GSHEETS_REFRESH_TOKEN}}
          
