name: Deploy

on:
  push:
    branches:
      - production 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_TOKEN}}
          heroku_app_name: "pap-bot"
          heroku_email:  ${{secrets.CREATOR_EMAIL}}
        env:
          BOT_ID: ${{secrets.BOT_ID}}
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          DATABASE_URL: ${{secrets.DATABASE_URL}}
          GCALENDAR_CLIENT_ID: ${{secrets.GCALENDAR_CLIENT_ID}}
          GCALENDAR_PROJECT_ID: ${{secrets.GCALENDAR_PROJECT_ID}}
          GCALENDAR_CLIENT_SECRET: ${{secrets.GCALENDAR_CLIENT_SECRET}}
          GCALENDAR_ACCESS_TOKEN: ${{secrets.GCALENDAR_ACCESS_TOKEN}}
          GCALENDAR_REFRESH_TOKEN: ${{secrets.GCALENDAR_REFRESH_TOKEN}}
          GMAIL_CLIENT_ID: ${{secrets.GMAIL_CLIENT_ID}}
          GMAIL_PROJECT_ID: ${{secrets.GMAIL_PROJECT_ID}}
          GMAIL_CLIENT_SECRET: ${{secrets.GMAIL_CLIENT_SECRET}}
          GMAIL_ACCESS_TOKEN: ${{secrets.GMAIL_ACCESS_TOKEN}}
          GMAIL_REFRESH_TOKEN: ${{secrets.GMAIL_REFRESH_TOKEN}}
          GDRIVE_FILE_ID: ${{secrets.GDRIVE_FILE_ID}}
          GDRIVE_CLIENT_ID : ${{secrets.GDRIVE_CLIENT_ID}}
          GDRIVE_PROJECT_ID: ${{secrets.GDRIVE_PROJECT_ID}}
          GDRIVE_CLIENT_SECRET: ${{secrets.GDRIVE_CLIENT_SECRET}}
          GDRIVE_ACCESS_TOKEN: ${{secrets.GDRIVE_ACCESS_TOKEN}}
          GDRIVE_REFRESH_TOKEN: ${{secrets.GDRIVE_REFRESH_TOKEN}}
          
